virtee/sev

src/certs/mod.rs
src/session/mod.rs

std::io::* imports std::io::Chain.
The sev crate exports its own Chain.
This confuses the vscode rust-analyzer plugin.
Drop the wildcard and explicilty list every std::io bit the affected
files use. IMO this makes for more readable code too.

Expand std::io wildcard `use` declarations

---

Cargo.toml
README.md

Cargo.toml and README.md badges still point to enarx github.
Switch them to virtee

Convert more enarx -> virtee references

---

Cargo.toml
src/vmsa/mod.rs

This tweaks the newly added vmsa API to be a bit more consistent with other `sev` code
* Use standard io::Result and io::Error
* Use codicon encode and decode methods for serializing
This also added a VMSA file length check on file input, to match the padding we do when writing to file. See individual commit messages for more details.

vmsa API tweaks

---

src/session/mod.rs

In some cases, such as when the digest of each launch measurement is
pre-generated beforehand, it's useful to be able to verify an
externally generated digest instead of having to pass the payload data
through Session<Measuring>::update_data().
This change implements Session<Measuring>::verify_with_digest(), which
behaves in the same way as Session<Measuring>::verify() but verifying
a digest that is provided as an argument to the method.
Signed-off-by: Sergio Lopez <slp@redhat.com>

session: allow verifying an external digest

---

Cargo.toml
src/launch/sev.rs
tests/launch.rs

Instead of a `sev::Launcher` taking references to `AsRawFd` implementers, allow then to take ownership if they see fit. If a caller does not want a `sev::Launcher` to take ownership, they can use `as_raw_fd()`.

launch/sev: Remove lifetime requirement

---

README.md
src/lib.rs

The links are missing an `src` prefix.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>

README: Fix links

---

.github/workflows/test.yml

- Removed build specific targer for 1.51.0, as it is unclear why it was specified in the CI yaml.
Addresses #34 
Signed-off-by: Larry Dewey <larry.dewey@amd.com>

CI: Reducing CI Targets

---

src/firmware/linux/host/ioctl.rs
src/firmware/linux/host/types.rs
src/firmware/uapi/host/mod.rs
src/firmware/uapi/host/types.rs
tests/api.rs

- Added in FFI wrappers for Snp Extended Report Features.
- Added in user apis for interacting with the FFI.
- Added in some unit tests and system tests for validating behavior.
Signed-off-by: Larry Dewey <larry.dewey@amd.com>

snp: Adding extended report features

---

Cargo.toml
src/firmware/host/mod.rs

97f02e02ea dropped this from the public API, but `sevctl show flags` still needs it

Revive PlatformStatusFlags export

---

src/firmware/guest/mod.rs

The fix in #30 allows us to use the passed `ext_report_request` argument as-is.
No functional change intended.
Signed-off-by: Dov Murik <dov.murik1@il.ibm.com>

firmware/guest: Simplify snp_get_ext_report()

---

src/certs/sev/cert/v1/sig/ecdsa.rs
src/firmware/guest/mod.rs
src/firmware/host/types.rs
src/firmware/linux/guest/types.rs
src/firmware/linux/host/types.rs

This is a set of commits to update the extended report API to return the contents of the report and the certificates in a rust-friendly way. It also adds derived serialization and de-serialization to the associated data types to allow easier marshaling between services.
Addresses #43 
Signed-off-by: Larry Dewey <larry.dewey@amd.com>

Update Extended Report APIs

---

src/certs/ca/cert/mod.rs
src/certs/sev/cert/mod.rs
src/firmware/host/types.rs
src/firmware/linux/guest/types.rs

Previously there was no way to access the policy or platform info fields. This patches those fields.
Signed-off-by: Larry Dewey <larry.dewey@amd.com>

policy: Fixing bitfield bugs

---

Cargo.toml

Update kvm-ioctls (and kvm-bindings) dependency to the latest available version (0.12.0) and relax the dependency in a optimistic way accepting any future version (this simplifies distro packaging).
Signed-off-by: Sergio Lopez <slp@redhat.com>

Update and relax kvm-ioctls dependency

---

.rustfmt.toml

Add .rustfmt.toml configuration file that sets checking options for rustfmt and cargo fmt. Start basic configuration that enforces edition from 2021 and Unix style, which is the case for prior code history.
Signed-off-by: Carlos Bilbao <carlos.bilbao@amd.com>

rustfmt: Add configuration file .rustfmt.toml

---

src/firmware/guest/mod.rs
src/firmware/linux/guest/types.rs

Between v1.0 and v1.1, the public API changed to match the underlying ioctl API, which could potentially modify request objects. This is not necessary for the following functions, because:
- snp_get_report: the kernel does not write into the request object (and there are no fields for which it would make sense)
- snp_get_ext_report: the request object is copied into the extended request object expected by the ioctl. The kernel returns the certificate length in the request object but we hide this from the caller.
- snp_get_derived_key: the passed request object is copied before passing to the ioctl.

guest: Remove '&mut' from some public APIs

---

src/firmware/host/mod.rs

According to the specification, in order to reset the `REPORTED_TCB`, it is required that `snp_set_ext_config` receive a configuration with a TcbVersion of 0. Previously I was just sending a configuration address of zero, which does nothing.

snp_reset: Fixing the snp_reset API

---

Cargo.toml
src/firmware/guest/mod.rs
src/firmware/linux/guest/types.rs
src/firmware/linux/host/types/snp.rs
src/launch/linux/ioctl.rs
src/launch/sev.rs
src/launch/snp.rs
tests/launch.rs
tests/snp_launch.rs

We only use `mmarinus` to allocate a 1kB page of memory in our tests. `libc`'s `mmap` can do this for us.

tests: Deprecate mmarinus, use libc's mmap

---

Cargo.toml

This PR proposed to declare minimal Rust version in `Cargo.toml`.
Explicitly declaring the minimal version can help developers.
The version is considered what `cargo msrv` says.
```
$ cargo msrv
...
Finished The MSRV is: 1.66.1 
```

Declare minimal Rust version in Cargo.toml.

---

.github/workflows/lint.yml
src/firmware/linux/host/types/snp.rs
tests/launch.rs
tests/snp_launch.rs

This PR aims to cleanup meaningless code.
They are detected by `cargo clippy --all-features --all-targets -- -D clippy::all -D unused_imports -Dwarnings`, and I suggest to do clippy with these options in CI.

Cleanup meaningless code.

---

.github/workflows/test.yml
Cargo.toml
src/certs/sev/crypto.rs
src/firmware/guest/mod.rs
src/firmware/host/mod.rs
src/firmware/linux/guest/mod.rs
src/firmware/linux/host/mod.rs
src/firmware/linux/host/types/mod.rs
src/firmware/linux/host/types/sev.rs
src/firmware/linux/host/types/snp.rs
src/launch/linux/mod.rs
src/lib.rs
tests/launch.rs

Fully support Windows & MacOS compilation. The attestation report can only be generated on Linux whereas the attestation report management such as parsing or verification can be proceeded on Linux, MacOS and Windows.
```sh
$ sudo apt-get install --no-install-recommends -qq libclang-dev gcc-mingw-w64-x86-64
$ rustup target add x86_64-pc-windows-gnu
$ rustup target add x86_64-apple-darwin
$ cargo build  --target  x86_64-pc-windows-gnu --features snp,sev,openssl
$ cargo build  --target  x86_64-apple-darwin --features snp,sev,openssl
```

Compile on windows & macOS

---

.github/workflows/lint.yml
.github/workflows/test.yml
Cargo.toml
README.md
src/certs/snp/builtin/genoa/mod.rs
src/certs/snp/builtin/milan/mod.rs
src/certs/snp/cert.rs
src/certs/snp/cert_nossl.rs
src/certs/snp/ecdsa/mod.rs
src/certs/snp/mod.rs
src/firmware/guest/types/snp.rs
src/lib.rs
tests/certs.rs

Allows the verification of an SNP `AttestationReport` without the use of OpenSSL through a new feature called `crypto_nossl`.
In particular, with `crypto_nossl` enabled, the `certs::snp::Verifiable` trait becomes implemented in pure Rust using the `p384`, `rsa`, `x509-cert`, and `sha2` crates, that is, without the use of OpenSSL, for the following types:
* `&certs::snp::Chain`
* `&certs::snp::ca::Chain`
* `(&certs::snp::Certificate, &certs::snp::Certificate)`
* `(&certs::snp::Chain, &firmware::guest::AttestationReport)`
This addresses https://github.com/virtee/sev/issues/109.
* Adapts the feature gate for the SNP tests in `tests/certs.rs` so that those tests are run if either `openssl` or `crypto_nossl` is enabled.
* Adds negative tests for the SNP chain and report.
* Adds a …

Allow verification of SNP AttestationReport without OpenSSL

---

src/launch/sev.rs

By registering KvmEncRegion, we can inform KVM about all memory owned by the SEV virtual machine. On the other hand, update_data can be utilized to encrypt the data we load into this memory. It's important to note that idle regions may not require encryption as they can be initialized by the VM's firmware or OS.
In the current API, these two operations are bundled together, resulting in unnecessary time consumption. Consequently, I have introduced two separate methods.

launch/sev: separate KVM ENC region registration from update_data

---

src/firmware/host/mod.rs
src/firmware/host/types/snp.rs

Previously we were passing the u64 value of the pointer to the vector of bytes the extended report certificates were being loaded from. However, when handling the case of an extended configuration only, because the pointer value of an empty vector is not 0, this was causing an error in the kernel when attempting to access the "pointer" being provided. By modifying the underlying type of `bytes` to `Option<Vec<u8>>`, it allows the default value to be set to `None`, and conditionally update the extended config `certs_address` field when certificate bytes are present.

ext_config: Fixes config only operations.

---

src/firmware/guest/mod.rs

Related to https://github.com/virtee/sev/issues/122 discussed with @tylerfanelli 
Is is possible to review and merge please? 
Thanks

Fix panic when querying an extended report without certs

---

src/firmware/guest/types/snp.rs

- adding guest policies for CXL_ALLOW, MEM_AES_256_XTS, RAPL_DIS, and CIPHERTEXT_HIDING fields.
- ensuring comments reflect the current documentation on what each of those fields does.
- [Issue 144](https://github.com/virtee/sev/issues/144)
- `cargo test`
```
Compiling futures-sink v0.3.28
Compiling pin-project-lite v0.2.13
Compiling scopeguard v1.2.0
Compiling futures-io v0.3.28
Compiling bitflags v1.3.2
Compiling cfg-if v1.0.0
Compiling libc v0.2.150
Compiling futures-core v0.3.28
Compiling slab v0.4.9
Compiling futures-task v0.3.28
Compiling smallvec v1.11.1
Compiling memchr v2.6.4
Compiling pin-utils v0.1.0
Compiling option-ext v0.2.0
Compiling lazy_static v1.4.0
Compiling serde v1.0.192
Compiling hashbrown v0.14.1
Compiling once_cell v1.18.0
Compiling log v0.4.20
Compiling lock_api …
```

Expanding Guest Policy Fields

---

Cargo.lock
Cargo.toml
src/firmware/host/mod.rs
src/firmware/host/types/snp.rs
src/firmware/linux/host/ioctl.rs
src/firmware/linux/host/types/snp.rs
tests/api.rs

In new kernel 6.6 the SNP IOCTL structure changed. We are completely removing the deprecated extended config and IOCTLs. I also bumped the release to 3.0 in this PR. THIS WILL NOT WORK ON KERNELS BEFORE SNP 6.6.
The new IOCTLS and it's uses have been added to this PR. 
SNP_SET_CONFIG_START and SNP_SET_CONFIG_END will be revised in later kernel patches according to Michael Roth. So those will probably be changed. Should we include those in this PR? 
Also certificates are no longer handled by firmware, but they will be handled by the QEMU command line. Do we want to move the kernel version of CertTableEntry to the UAPI? that way users can create the appropriate versions of that? For now there will be some compiling errors because that struct is not being used, but I don't think it has been …

Changing API for kernel 6.6 new IOCTL structure

---

src/certs/snp/chain.rs
src/firmware/host/types/snp.rs
tests/certs.rs

This adds support for handling Version Loaded Endorsement Keys and Certificate Revocation Lists.

vlek: Adding VLEK support

---

src/certs/snp/cert.rs
src/error.rs

Adding generic support to automatically identify which type of certificate the user provided and construct a Certificate from the identity discovered.
Also adds an explicit `openssl` feature flag instead of relying on the inferred flag.

Certs: Adding generic support.

---

src/certs/snp/cert.rs

There was a bug where we were comparing the whole
byte stream instead of the first 27 bytes of data.

152: Fixing cert identifier bug

---

.github/workflows/lint.yml
.github/workflows/test.yml

GA workflow raises lots of warnings.
https://github.com/virtee/sev/actions/runs/6180387727
To deal with the warnings, I propose to update workflow files.

Modify workflow files to deal with warnings

---

Cargo.lock
Cargo.toml
src/firmware/host/types/snp.rs

Adding Ord and Partial Ord to:
- firmware::host::types::snp::CertType
- firmware::host::types::snp::CertTableEntry
This will allow for sorting of a `Vec<CertTableEntry>` which, when sorted, will place the order as such:
ARK < VCEK < VLEK < ASK < CRL < OTHER < Empty
Making ARK the first in a sorted vect, etc.

Certificates: Adding Ord and PartialOrd

---

Cargo.lock
Cargo.toml
src/firmware/guest/mod.rs

This adds missing functionality to automatically sort certifactes obtained by an extended guest request

certs: Auto sort extended guest request certs

---

README.md
src/lib.rs

Correct the links at the crate docs

---

src/firmware/guest/types/snp.rs

The order of the TSME and the SMT bit was wrong.
Also added ECC, RAPL and Ciphertext hiding bits to PlatformInfo, as defined in Table 23 of 
https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf

Fixed wrong order in PlatformInfo and added missing bits

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
README.md
src/firmware/host/types/snp.rs
src/firmware/linux/host/types/snp.rs
src/lib.rs
src/measurement/gctx.rs
src/measurement/mod.rs
tests/api.rs
tests/guest.rs
tests/id-block.rs
tests/launch.rs
tests/measurement.rs
tests/session.rs
tests/snp_launch.rs

The SEV library was compiling on MacOS & Windows previously. Recent commits have broken that. This PR fixes it. 
Also add MacOS & Windows runners in the CI workflow to keep MacOS & Windows support in the future

Fix MacOS & Windows compilation

---

src/firmware/guest/types/snp.rs
src/launch/snp.rs
tests/snp_launch.rs

Unifies the duplicated `GuestPolicy` definition, as discussed in https://github.com/virtee/sev/issues/165  .
I am not quite happy with the "ergonomics" of the bitflags! macro. If I am not overlooking something, it requires to instantiate a mutable variable and use the set_XXX functions to create an instance using the bit definitions. Crates like [modular_bitfield](https://docs.rs/modular-bitfield/0.11.2/modular_bitfield/) seem more ergonomic, but I don't have a good overview of the available crates for this problem space

Unify Duplicated GuestPolicy Definitions

---

.github/workflows/lint.yml
README.md
build.sh
src/cargo-build.sh
src/error.rs
src/firmware/guest/mod.rs
src/firmware/guest/types/snp.rs
src/firmware/host/types/snp.rs
src/firmware/linux/guest/types.rs
src/firmware/linux/host/types/snp.rs
src/lib.rs

Utilizing `cargo-rdme` as an alternative to `cargo readme` to fix the broken links between github and crates.io.
Resolves: #169

Docs: Fixing broken documentation links.

---

Cargo.lock
Cargo.toml

Update kvm-ioctls from 0.15.0 to 0.16.0 and kvm-bindings to 0.7.0
Fixes: https://github.com/virtee/sev/issues/173

Update kvm-ioctls from 0.15.0 to 0.16.0

---

src/error.rs
src/firmware/host/mod.rs
src/firmware/linux/host/ioctl.rs
src/firmware/linux/host/types/snp.rs

Adding in ioctls for SNP_VLEK_LOAD to allow platform owners to load VLEK where appropriate.

vlek: Adding vlek ioctls

---

Cargo.lock
Cargo.toml
src/certs/snp/ca/mod.rs
src/certs/snp/cert.rs
src/certs/snp/chain.rs

- Made X509 within Certificate pub (requires major version bump).
- Added in a bunch of additional support for translating between `Certificate`, `openssl::X509`, `ca::Chain`, and `Chain`

certs: Adding additional functionality.

---

.github/workflows/lint.yml
src/firmware/linux/host/ioctl.rs
src/session/mod.rs

Adding additional clippy style check to clean up linting errors.

clippy: Adding clippy::style check

---

src/measurement/vmsa.rs

GuestFeatures should default to 0x1 like the kernel does.

Adding correct default value for GuestFeatures

---

Cargo.lock
Cargo.toml
src/error.rs
src/session/key.rs
src/session/mod.rs

According to the documentation, openssl's `rand_bytes(...)` function will be seeded with `/dev/urandom`, which is not sound for cryptographic application. We will be switching to using the `rdrand` crate which will utilize the X86_64 microcode call to `RDRAND`, instead. All X86_64 instructions are protected by the Guest Hypervisor Communication Block (GHCB), and may thus be presumed secure for cryptographic practices in the context of confidential compute.
Obviously this introduces a change to the API, requiring a new major release of the crate.
Resolves: #189

rand: Removing use of openssl rand for crypto

---

src/certs/sev/ca/cert/mod.rs
src/certs/sev/ca/cert/v1.rs
src/certs/sev/ca/chain.rs
src/certs/sev/crypto.rs
src/certs/sev/sev/cert/mod.rs
src/certs/sev/sev/cert/v1/algo.rs
src/certs/sev/sev/cert/v1/body/key/ecc/group.rs
src/certs/sev/sev/cert/v1/body/key/mod.rs
src/certs/sev/sev/cert/v1/body/key/rsa.rs
src/certs/sev/sev/cert/v1/mod.rs
src/certs/sev/sev/cert/v1/sig/mod.rs
src/certs/sev/sev/chain.rs
src/firmware/guest/mod.rs
src/launch/sev.rs
src/measurement/gctx.rs
src/measurement/ovmf.rs
src/measurement/sev_hashes.rs
src/session/mod.rs

Recently learned the more idomatic solution is to use the question mark operator instead of using .into() when casting error types.

cleanup: Removing unnecessary .into() calls

---

meson.build

- **Chores**
- Updated the project version retrieval method to specify the Python interpreter, enhancing compatibility across different environments.

Update meson build to specify python

---

Cargo.lock
Cargo.toml
src/launch/linux/ioctl.rs
src/launch/linux/mod.rs
src/launch/linux/shared.rs
src/launch/linux/snp.rs
src/launch/sev.rs
src/launch/snp.rs
tests/launch.rs
tests/snp_launch.rs

Updated the launch library to use INIT2 IOCTL and deprecate the old INIT IOCTLs. Created new functions to register encrypted memory for SNP. Updated SEV test to use INIT2. Updated the SNP launch test to use GMEM and support KVM GMEM for launch.

Updated launch library to use current IOCTls and gmem

---

Cargo.lock
Cargo.toml
src/error.rs
src/firmware/guest/mod.rs
src/firmware/host/mod.rs
src/firmware/linux/guest/ioctl.rs
src/firmware/linux/host/ioctl.rs
src/launch/linux/ioctl.rs
src/launch/sev.rs
src/launch/snp.rs
src/lib.rs
tests/api.rs
tests/guest.rs

The AMD PSP provides defined SEV errors in the API with clear codes and mistakes. The library currently only bubbles up IO errors and not the correct SEV error when IOCTL calls fail. This commit rearranges the error file to use SEV errors correctly, and then changes the way IOCTL calls returns errors, so that the appropriate SEV error is bubbled up when an error is encountered.

Updating Errors to correctly use SEV API errors

---

Cargo.toml

Without the `dep:_` prefix, packagers can mistake this for being a feature, rather than the enablement of an optional dependency.

Cargo.toml: Specify rdrand as dependency

---

src/firmware/guest/types/snp.rs

Since version 2 of the attestation report, instead of having just the AUTHOR_KEY_EN fIELD in the attestation report, the report now offers more data around the signature and the key being used in the attestation report. This PR extends that field and makes it accessible in the attestation report.
(This has been in the spec since sept 2023, unrelated to upcoming changes)

Adding the KeyInfo field into the attestation report

---

src/firmware/host/types/snp.rs

Initially, byte 0x3 of STRUCT_PLATFORM_STATUS only used bit 0 to indicate if the RMP was initialized. Updates were made to include bitfields to indicate if alias detection has completed since the last system reset and there are no aliasing addresses (bit 1), as well as if SEV-TIO is enabled (bit 3).

firmware/snp: Update 0x3 platform initialization data

---

src/firmware/guest/types/snp.rs

We currently only offer report verification with a full chain being provided. Although it is safest to provide a whole chain to verify the whole root of trust, there are cases people might want to divide the process into individual steps. This allows users to verify the report with what should be an already verified versioned endorsement key.
I also renamed the VCEK to VEK since we no offer support for both the VLEK and VCEK.

Adding AttestationReport Verification with Certificate only

---

src/certs/sev/sev/cert/v1/sig/ecdsa.rs
src/firmware/host/types/sev.rs

Hi folks,
For a couple of weeks, I've been investigating AMD SEV technology and experimenting with the `sev/sevctl` tool. I noticed that legacy report validation was only drafted (rewritten from the deprecated `sev-tool`) but actually does not work as expected. I've fixed that and tried to mimic the spirit of the `sevctl` tool as much as possible. This is my first contribution in Rust, so your feedback is highly appreciated.
What has been done in this PR:
* Corrected signature verification to use the SHA256 digest instead of raw data.
* Fixed signature size in `LegacyAttestationReport` by defining it as an `Array<u8, 144>` instead of an `EcdsaSignature` structure, which is 512 bytes.
* Fixed digest size in `LegacyAttestationReport`, ensuring `launch_digest` uses `DIGEST_SIZE` instead of …

Fix legacy attestation report validation

---

Cargo.lock
Cargo.toml
src/firmware/linux/host/types/sev.rs
src/launch/sev.rs
src/launch/snp.rs

- Upgrading to vendored openssl.
- Updating dependency libraries.

Switching to vendored openssl

---

src/certs/snp/ecdsa/mod.rs
src/firmware/guest/types/snp.rs

Although exceptionally rare, adding support for Turin V2 Reports. Also checking to make sure mask_chip_id is handled appropriately, as well. Should be a patch release.

Adding support for Turin V2 Reports

---

src/error.rs
src/firmware/guest/types/snp.rs

Previously we assumed that `MASK_CHIP_KEY` also contained information identifying if `MASK_CHIP_ID` was enabled. This was unfortunately incorrect, so the only method remaining to see if `MASK_CHIP_ID` is enabled is to see if the full value of the `CHIP_ID` is zeroed.

AttestationReport: Fixing turin-like check fn

---

src/measurement/idblock.rs

It turns out that OpenSSL generates several types of PEM formats for private keys. The 'BEGIN PRIVATE KEY' is the PKCS8 format, but previously there was the EC 'legacy', which can still be used and generated successfully by OpenSSL. Among these, there are also encrypted PEM keys, which start with the 'BEGIN ENCRYPTED PRIVATE KEY' line and can also be used.
This patch extends support for PEM formats by adding two more: EC legacy ("BEGIN EC PRIVATE KEY") and PKCS8 encrypted ("BEGIN ENCRYPTED PRIVATE KEY").
Why bother? The following commands are all valid and generate three PEM keys:
```bash
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:secp384r1 -out id-block-key.pem
```
```bash
openssl ecparam -name secp384r1 -genkey -noout -out id-block-key.pem
```
```bash
openssl genpkey …
```

idblocks: support a few other PEM formats

---

src/firmware/guest/types/snp.rs

Generating a report with `snpguest` tooling on a VM running on GCP with report version `4` and firmware version `1.55.31` on a Milan CPU is getting saved as Turin report. Therefore a malformed report is getting saved and verification is failing.
As I have not found any public information about version `4` of the report structure and the verification of the report is successful with `snpguest` tooling including this fix, I assume that no major changes have occured to the report structure.
References:
https://github.com/google/go-sev-guest/pull/158/files Changes to googles SEV go library for report version `4` and firmware `1.55.31`.

Firmware: Fix attestation report save to file for report versions >=3 on preTurin

---

Cargo.toml

Want to bump to 6.2.0 to have the last 2 PRs, since they both include some bug fixes.

Bumping version to 6.2.0

---

Cargo.lock
Cargo.toml
src/firmware/guest/types/snp.rs

An overlook on the last PR. Commited TCBs are being written wrong for v3 Pre-turins. This fix takes care of that issue. Bump to a minor bug fix so we can release fix.

Fixing writing TCB bug and bumping to 6.2.1

---

src/firmware/guest/mod.rs
src/firmware/guest/types/snp.rs
src/firmware/host/types/snp.rs
src/firmware/linux/guest/types.rs
tests/guest.rs

The new 1.58 firmware specification has been released, introducing changes to both the attestation report and key derivation features.
Attestation Report Changes:
Two new fields have been added: launch_mit_vector and current_mit_vector. These vectors reflect mitigations that may or may not be present on the system. Additionally, a new enablement bit for SEV-TIO has been added to the PlatformInfo structure. The attestation report version is now bumped to version 5. (Note: Version 4 remains under AMD embargo, so specifics cannot be disclosed.)
Key Derivation Changes:
A new field, launch_mit_vector, has been added to the key derivation request structure. This allows a mitigation vector to be mixed into the derived key. As a result, the message key request has been bumped to version 2. …

Updating Library to Match Version 1.58 of the SNP Spec

---

src/firmware/host/mod.rs
src/firmware/host/types/snp.rs
src/firmware/linux/host/types/snp.rs
tests/api.rs

When we updated the TCB structure, we overlooked modifying the config-related structures to account for differences in TCB layout across CPU generations.
This commit ensures that raw TCB bytes are correctly constructed for the FFI layer, and that conversions from the user-level structure to the FFI format use the appropriate TCB structure based on the processor generation.

Fix: Update Config structures to accurately reflect TCBs

---

src/firmware/guest/types/snp.rs
src/lib.rs

There is no reason to keep the `From<Generation> for CertSevCaChain` and `From<Generation> for CertSnpCaChain` implementations gated on the `openssl` feature. `CertSevCaChain` is available behind the `sev` feature and `CertSnpCaChain` is available when either `openssl` or `crypto_nossl` is active besides `sev`.

Refactor: Open up Generation -> CerXXXCaChain converters

---

Cargo.toml

We're working with SEV on a platform that is not supported by vendored Openssl (Yocto with OpenEmbedded, not supported by the crate openssl-src, and we spent a couple hours trying to hack together a workaround for vendored OpenSSL to no avail). We've been able to make do with version 6.0.0 for a while, but we're in need to update to 6.2.1 due to https://github.com/virtee/sev/commit/e96d605b672fae3c50fddbf2ae82fb6c1aee7673.
This change preserves the intent of OpenSSL being vendored by default if enabled, but leaves the possibility for dependents to disable OpenSSL vendoring.

Allow OpenSSL vendoring to be disabled

---

src/lib.rs

When this crate is used to parse SNP hardware evidence on a non-x86 platform, it will still try to build with cpuid from the x86 crate, which will not be found.
Instead, put cpuid behind a platform config flag. If we are not on x86, don't call cpuid and return an error.
Fixes #326 
As an aside, it seems kind of odd that we call this from the types code.

snp: skip calling CPUID on non-x86 platform

---

Cargo.toml
src/error.rs

This changes the dependency logic so instead of requiring the `rdrand` dependency when the `openssl` feature is on, it does so when the `sev` feature is on.
The logic here is `rdrand` is only used in the `session` module, which is only enabled [if the `sev` feature flag is on](https://github.com/virtee/sev/blob/main/src/lib.rs#L105-L106). Therefore, while you also need `openssl` to be enabled, it's more accurate to require `rdrand` when you want to use `sev` and not when you're using `openssl` since this code is tied to SEV code than it is to openssl (e.g. this is part of the SEV functionality AFAICT).
The deeper motivation here is that `rdrand` [doesn't work in arm](https://github.com/nagisa/rust_rdrand/issues/20), which is fine in general, but I'm trying to compile some code that is …

feat: require `rdrand` only when `sev` feature is on
